checks:
  php: true
filter:
  excluded_paths:
    - 'tests/*'
build:
  environment:
    php:
      version: 5.6
  tests:
      override:
          -
              command: 'vendor/bin/phpunit --coverage-clover=coverage'
              coverage:
                  file: 'coverage'
                  format: 'php-clover'
